In [12]:
import torch
import numpy as np

#1D
t1=torch.tensor([1,2,3,4])
print(t1,t1.shape)
a1=np.array([1,2,3,4])
print(a1,a1.shape)

tensor([1, 2, 3, 4]) torch.Size([4])
[1 2 3 4] (4,)


In [13]:
#2D
t2=torch.tensor([[1,2,3],
                   [4,5,6]])
print(t2, t2.shape)
a2=np.array([[1,2,3],
               [4,5,6]])
print(a2,a2.shape)

tensor([[1, 2, 3],
        [4, 5, 6]]) torch.Size([2, 3])
[[1 2 3]
 [4 5 6]] (2, 3)


In [14]:
# 3D
t3=torch.tensor([[[1,2,3],
                    [4,5,6]],
                   [[7,8,9],
                    [10,11,12]]])
print(t3,t3.shape)
a3 = np.array([[[1,2,3],
                [4,5,6]],
               [[7,8,9],
                [10,11,12]]])
print(a3,a3.shape)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]]) torch.Size([2, 2, 3])
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] (2, 2, 3)


In [15]:
x=torch.tensor([1,2,3])
y=torch.tensor([10,20,30])
print(x+y)
print(x-y)
print(x*y)
print(y/x)

tensor([11, 22, 33])
tensor([ -9, -18, -27])
tensor([10, 40, 90])
tensor([10., 10., 10.])


In [16]:
x=np.array([1,2,3])
y=np.array([10,20,30])
print(x+y)
print(x*y)

[11 22 33]
[10 40 90]


In [17]:
t=torch.tensor([1.0,4.0,9.0])

print(torch.sqrt(t))
print(torch.exp(t))
print(torch.log(t))


tensor([1., 2., 3.])
tensor([2.7183e+00, 5.4598e+01, 8.1031e+03])
tensor([0.0000, 1.3863, 2.1972])


In [18]:
a=np.array([1.0,4.0,9.0])
print(np.sqrt(a))

[1. 2. 3.]


In [19]:
t=torch.tensor([10,20,30,40])
print(t[0])
print(t[-1])
print(t[1:3])

tensor(10)
tensor(40)
tensor([20, 30])


In [20]:
m=torch.tensor([[1,2,3],
                  [4,5,6]])

print(m[0])
print(m[:,1])
print(m[0,2])
print(m[:,1:3])

tensor([1, 2, 3])
tensor([2, 5])
tensor(3)
tensor([[2, 3],
        [5, 6]])


In [21]:
t3=torch.arange(24).reshape(2,3,4)
print(t3[0])
print(t3[0,1])
print(t3[:,:,2])

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([4, 5, 6, 7])
tensor([[ 2,  6, 10],
        [14, 18, 22]])


In [22]:
t=torch.tensor([1,5,10,15,2])
mask=t>5
print(mask) 
print(t[mask])

tensor([False, False,  True,  True, False])
tensor([10, 15])


In [23]:
a=np.array([1,5,10,15,2])
print(a[a>5])

[10 15]


In [24]:
a=torch.tensor([[1,2,3],[4,5,6]])
mask=a>3
a[mask]

tensor([4, 5, 6])

In [25]:
a=np.array([[1,2,3],[4,5,6]])
a[a>3]

array([4, 5, 6])

In [26]:
a=torch.arange(1,13).reshape(3,4)
a[0:2,1:3]

tensor([[2, 3],
        [6, 7]])

In [27]:
a=torch.arange(1,13).reshape(3,4)
rows=torch.tensor([0,2])
cols=torch.tensor([1,3])
a[rows]
a[:,cols]

tensor([[ 2,  4],
        [ 6,  8],
        [10, 12]])

In [28]:
a=torch.arange(24).reshape(2,3,4)
a[0]
a[:,1]
a[a>10]

tensor([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [29]:
a=torch.arange(12)
a.view(3,4)
a.reshape(2,6)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

In [30]:
a=torch.tensor([1,2,3])
a.unsqueeze(0)
a.unsqueeze(1)

b=torch.randn(1,3,1,5)
b.squeeze()
b.squeeze(0)

tensor([[[ 0.0469, -2.4618, -0.3571, -0.2109,  0.3048]],

        [[ 1.1072, -0.4551,  0.2062,  0.1702,  0.7884]],

        [[ 1.1676, -0.5128, -0.2724, -0.2778,  0.3063]]])

In [31]:
a=np.arange(12)
a.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
a=torch.tensor([[1,2,3],[4,5,6]])
b=torch.tensor([10,20,30])
a+b

c=torch.tensor([[100],[200]])
a+c

tensor([[101, 102, 103],
        [204, 205, 206]])

In [33]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([10,20,30])
a+b

array([[11, 22, 33],
       [14, 25, 36]])

In [34]:
a=torch.tensor([1,2,3])
b=a+5

In [35]:
a=torch.tensor([1,2,3])
a.add_(5)
a.mul_(2)

tensor([12, 14, 16])